config/routes.rb
Rails.application.routes.draw do
 
  get 'users/new'

 resources :articles
 resources :customers
 resources :companies

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 5}

end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books 
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :stocks , inverse_of: :Company
	has_many :phones, as: :callable
end

app/models/customer.rb
class Customer < ApplicationRecord
   has_many :stocks, dependent: :destroy
  validates :fname, presence: true, length: {minimum:3}
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord

belongs_to :page

end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :callable, polymorphic: true
end

app/models/stock.rb
class Stock < ApplicationRecord
  
end

app/models/sub.rb
class Sub < ApplicationRecord

has_one :sub

scope :visible, lambda { where(:visible=>true)}
scope :invisible, lambda { where(:visible=>false)}
scope :sorted, lambda {order("position ASC")}
scope :newest_first, lambda {order("created_at DESC")}
scope :search, lambda{|query| where(["name LIKE ?","%#{query}%"])}


end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
def index
	@articles = Article.all
end


 def show
  	@article = Article.find(params[:id])
  end

def new
	@article = Article.new
end

def create
	@article = Article.new(article_params)

	if @article.save
	redirect_to @article
    else
      render 'new'
      end	
end

private
  def article_params
  	params.require(:article).permit(:title, :text)
  end

 
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  	@login = Login.new
  end

  def create
  	@login = Login.new(params[:login])
  	if @login.save
  		redirect_to @login, notice: 'successfully created'
  	else
  		render action: 'new'
  	end
end

def show
	@login = Login.find(params[:id])
end

end

app/controllers/stock_controller.rb
class StockController < ApplicationController

def index
	@stocks = Stock.all
end

def create
  @stock = stock.new(stock_params)
  if @stock.save
	  flash[:notice]= 'stock saved successfully'
	  redirect_to @stock
    else
	  render 'new'
    end
end

def show
	@stock = Stock.find(params[:id])
end

def new
	@stock = Stock.new
end

private
def stock_params
	params.require(:stock).permit(:date, :description, :units, :price, :customer_id, :company_id)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>Listing articles</h1>
 <%= link_to 'new article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
  <%= f.label :date%><br>

  <%= f.date_select(:date, :order => [:month, :day, :year]) %>
    <%= f.date_select :dateinstructed,:order => [:day, :month, :year] %><br>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'back', articles_path %>