config/routes.rb
Rails.application.routes.draw do
 
  get 'users/new'

 resources :articles
 resources :customers
 resources :companies

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 5}

end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books 
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :stocks , inverse_of: :Company
	has_many :phones, as: :callable
end

app/models/customer.rb
class Customer < ApplicationRecord
   has_many :stocks, dependent: :destroy
  validates :fname, presence: true, length: {minimum:3}
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord

belongs_to :page

end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :callable, polymorphic: true
end

app/models/stock.rb
class Stock < ApplicationRecord
  
end

app/models/sub.rb
class Sub < ApplicationRecord

has_one :sub

scope :visible, lambda { where(:visible=>true)}
scope :invisible, lambda { where(:visible=>false)}
scope :sorted, lambda {order("position ASC")}
scope :newest_first, lambda {order("created_at DESC")}
scope :search, lambda{|query| where(["name LIKE ?","%#{query}%"])}


end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
before_action :authenticate_admin!

def index
  @customers = Customer.all
end

def show
	@customer = Customer.find(params[:id])
end

def new
	@customer = current_admin.customers.build
end

def create
	   @customer = current_admin.customers.build(customer_params)

	 if @customer.save
	 	flash[:notice] = "saved successfully"
	   redirect_to @customer
	else
		render action: 'new'
	 end
end

def destroy
	@customer = Customer.find(params[:id])
	@customer.destroy 
	redirect_to customers_path, :notice => "Deleted!!"
end


private
  def customer_params
  	params.require(:customer).permit(:lname, :mname, :fname,:dob,:add,:city,:state,:email)
  end	

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  	@login = Login.new
  end

  def create
  	@login = Login.new(params[:login])
  	if @login.save
  		redirect_to @login, notice: 'successfully created'
  	else
  		render action: 'new'
  	end
end

def show
	@login = Login.find(params[:id])
end

end

app/controllers/stock_controller.rb
class StockController < ApplicationController

def index
	@stocks = Stock.all
end

def create
  @stock = stock.new(stock_params)
  if @stock.save
	  flash[:notice]= 'stock saved successfully'
	  redirect_to @stock
    else
	  render 'new'
    end
end

def show
	@stock = Stock.find(params[:id])
end

def new
	@stock = Stock.new
end

private
def stock_params
	params.require(:stock).permit(:date, :description, :units, :price, :customer_id, :company_id)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/index.html.erb
<h1>Listing Customers</h1>
 
 <%= link_to 'New customer', new_customer_path %>

<table>
  <tr>
    <th>Last name</th>
    <th>Middle Name</th>
    <th>First Name</th>
    <th>Date of birth</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Email</th>
  </tr>
 
  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.lname %></td>
      <td><%= customer.mname %></td>
      <td><%= customer.fname %></td>
      <td><%= customer.dob %></td>
      <td><%= customer.add %></td>
      <td><%= customer.city %></td>
      <td><%= customer.state %></td>
      <td><%= customer.email %></td>
      <td><%= link_to 'Show', customer_path(customer) %></td>
    </tr>
  <% end %>
</table>

app/views/customers/new.html.erb
  
<div class="containier" style="max-width:50%; align-self: center;" >
<%= simple_form_for @customer do |f| %>
<% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@customer.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @customer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%= f.input :lname, placeholder: 'last name', label: false %>
<%= f.input :mname, placeholder: 'middle name', label: false %>
<%= f.input :fname, placeholder: 'first name', label: false %>
<%= f.input :dob %>
<%= f.input :add, placeholder: 'address', label: false %>
<%= f.input :city, placeholder: 'city' %>
<%= f.input :state, placeholder: 'state', label: false %>
<%= f.input :lname, placeholder: 'email', label: false %>
<%= f.button :submit %>
<%end%>
<%= link_to 'Back', customers_path %>
</div>

app/views/customers/show.html.erb
<p>
  <strong>last name:</strong>
  <%= @customer.lname %>
</p>

 <p>
  <strong>middle name:</strong>
  <%= @customer.mname %>
</p>

<p>
  <strong>first name:</strong>
  <%= @customer.fname %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @customer.dob %>
</p>

<p>
  <strong>Address:</strong>
  <%= @customer.add %>
</p>

<p>
  <strong>State:</strong>
  <%= @customer.state %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<%= link_to 'Back', customers_path %>