config/routes.rb
Rails.application.routes.draw do
 
  get 'users/new'

 resources :articles
 resources :customers
 resources :companies

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 5}

end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books 
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :stocks , inverse_of: :Company
	has_many :phones, as: :callable
end

app/models/customer.rb
class Customer < ApplicationRecord
   has_many :stocks, dependent: :destroy
  validates :fname, presence: true, length: {minimum:3}
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord

belongs_to :page

end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :callable, polymorphic: true
end

app/models/stock.rb
class Stock < ApplicationRecord
  
end

app/models/sub.rb
class Sub < ApplicationRecord

has_one :sub

scope :visible, lambda { where(:visible=>true)}
scope :invisible, lambda { where(:visible=>false)}
scope :sorted, lambda {order("position ASC")}
scope :newest_first, lambda {order("created_at DESC")}
scope :search, lambda{|query| where(["name LIKE ?","%#{query}%"])}


end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
before_action :authenticate_admin!


def index
	@companies = Company.all
end

def show
	@company = Company.find(params[:id])
end

def new
	@company = Company.new
end

def create
	@company = Company.new(company_params)

	if @company.save
	  flash[:notice]= 'company saved successfully'
	  redirect_to @company
    else
	  render 'new'
    end
end

def destroy
	@company = Company.find(params[:id])
	@company.destroy 
	redirect_to companies_path, :notice => "Deleted!!"
end

private
def company_params
	params.require(:company).permit(:name, :add, :city, :state, :email)
end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  	@login = Login.new
  end

  def create
  	@login = Login.new(params[:login])
  	if @login.save
  		redirect_to @login, notice: 'successfully created'
  	else
  		render action: 'new'
  	end
end

def show
	@login = Login.find(params[:id])
end

end

app/controllers/stock_controller.rb
class StockController < ApplicationController

def index
	@stocks = Stock.all
end

def create
  @stock = stock.new(stock_params)
  if @stock.save
	  flash[:notice]= 'stock saved successfully'
	  redirect_to @stock
    else
	  render 'new'
    end
end

def show
	@stock = Stock.find(params[:id])
end

def new
	@stock = Stock.new
end

private
def stock_params
	params.require(:stock).permit(:date, :description, :units, :price, :customer_id, :company_id)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/index.html.erb
<h1>Listing Companies</h1>
 
 <%= link_to 'New company', new_company_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Email</th>
  </tr>
 
  <% @companies.each do |company| %>
    <tr>
      <td><%= company.name %></td>
      <td><%= company.add %></td>
      <td><%= company.city %></td>
      <td><%= company.state %></td>
      <td><%= company.email %></td>
      <td><%= link_to 'Show', company_path(company) %></td>
    </tr>
  <% end %>
</table>

app/views/companies/new.html.erb
<%= simple_form_for @company do |f| %>
<% if @company.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@company.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @company.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name, placeholder: 'name', label: false %>
  <%= f.input :add, placeholder: 'address', label: false %>
  <%= f.input :city, placeholder: 'city', label: false %>
  <%= f.input :state, placeholder: 'state', label: false %>
  <%= f.input :email, placeholder: 'email', label: false %>
  <%= f.button :submit %>
  <%end%>
<%= link_to 'Back', companies_path %>
</div>

app/views/companies/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>
 <p>
  <strong>Address:</strong>
  <%= @company.add %>
</p>
<p>
  <strong>City</strong>
  <%= @company.city %>
</p>
<p>
  <strong>State:</strong>
  <%= @company.state %>
</p>
<p>
  <strong>Email</strong>
  <%= @company.email %>
</p>

<%= link_to 'Back', companies_path %>